/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --types
Author: FFXN (https://sketchfab.com/anuginethuka)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neon-female-bundel-freefire-1st-booyah-pass-875b0fe061484e81ad0ce28a6ba7b2dd
Title: NEON FEMALE BUNDEL FREEFIRE 1ST BOOYAH PASS
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
  };
  materials: {
    ["mat0_Mesh_0003.rip"]: THREE.MeshStandardMaterial;
    ["mat0_Mesh_0004.rip"]: THREE.MeshStandardMaterial;
    ["mat0_Mesh_0006.rip"]: THREE.MeshStandardMaterial;
    ["mat0_Mesh_0009.rip"]: THREE.MeshStandardMaterial;
    ["mat0_Mesh_0010.rip"]: THREE.MeshStandardMaterial;
  };
};

export function BooyahGirl(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "models/female/scene.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials["mat0_Mesh_0003.rip"]}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials["mat0_Mesh_0004.rip"]}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials["mat0_Mesh_0006.rip"]}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials["mat0_Mesh_0009.rip"]}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials["mat0_Mesh_0010.rip"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/female/scene.gltf");
