import Head from "next/head";
import Image from "next/image";
import { Bebas_Neue } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import ThreeScenes from "@/components/three/ThreeScenes";
import Tunnel from "@/components/three/Tunnel";
import InfinityTunnel from "@/components/three/Tunnel";
import { Canvas } from "@react-three/fiber";
import Intro from "@/components/hero/Intro";

// subsets?: ("latin" | "latin-ext")[] | undefined;

export default function Home() {
  return (
    <>
      <Head>
        <title>The Arcane Origins</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="h-[10vh] w-full bg-[#15151a]"></div>
        <ThreeScenes />
        <Intro />
        {/* <Tunnel /> */}
      </main>
    </>
  );
}
